{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "11ba34d7-8296-4322-a1fc-2dced8080a51",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import classification_report, accuracy_score\n",
    "import urllib.parse\n",
    "import numpy as np\n",
    "import pickle\n",
    "\n",
    "# List of bad words to check in the URL path\n",
    "badwords = ['sleep', 'uid', 'select', 'waitfor', 'delay', 'system', 'union', 'order by', 'group by', 'admin', 'drop', 'script']\n",
    "\n",
    "def ExtractFeatures(path, body):\n",
    "    path = str(path)\n",
    "    body = str(body)\n",
    "    combined_raw = path + body\n",
    "    raw_percentages = combined_raw.count(\"%\")\n",
    "    raw_spaces = combined_raw.count(\" \")\n",
    "\n",
    "    raw_percentages_count = raw_percentages if raw_percentages > 3 else 0\n",
    "    raw_spaces_count = raw_spaces if raw_spaces > 3 else 0\n",
    "\n",
    "    path_decoded = urllib.parse.unquote_plus(path)\n",
    "    body_decoded = urllib.parse.unquote_plus(body)\n",
    "\n",
    "    single_q = path_decoded.count(\"'\") + body_decoded.count(\"'\")\n",
    "    double_q = path_decoded.count(\"\\\"\") + body_decoded.count(\"\\\"\")\n",
    "    dashes = path_decoded.count(\"--\") + body_decoded.count(\"--\")\n",
    "    braces = path_decoded.count(\"(\") + body_decoded.count(\"(\")\n",
    "    spaces = path_decoded.count(\" \") + body_decoded.count(\" \")\n",
    "    semicolons = path_decoded.count(\";\") + body_decoded.count(\";\")\n",
    "    angle_brackets = path_decoded.count(\"<\") + path_decoded.count(\">\") + body_decoded.count(\"<\") + body_decoded.count(\">\")\n",
    "    special_chars = sum(path_decoded.count(c) + body_decoded.count(c) for c in '$&|')\n",
    "\n",
    "    badwords_count = sum(path_decoded.lower().count(word) + body_decoded.lower().count(word) for word in badwords)\n",
    "\n",
    "    path_length = len(path_decoded)\n",
    "    body_length = len(body_decoded)\n",
    "\n",
    "    return [single_q, double_q, dashes, braces, spaces, raw_percentages_count, semicolons, angle_brackets, special_chars, path_length, body_length, badwords_count]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "40b867e8-fc05-4bd3-b102-c9e069caa3c8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "method              0\n",
      "path                0\n",
      "body              418\n",
      "single_q            0\n",
      "double_q            0\n",
      "dashes              0\n",
      "braces              0\n",
      "spaces              0\n",
      "percentages         0\n",
      "semicolons          0\n",
      "angle_brackets      0\n",
      "special_chars       0\n",
      "path_length         0\n",
      "body_length         0\n",
      "badwords_count      0\n",
      "class               0\n",
      "dtype: int64\n",
      "Accuracy: 0.9238095238095239\n",
      "Classification Report:\n",
      "              precision    recall  f1-score   support\n",
      "\n",
      "           0       0.86      1.00      0.92        48\n",
      "           1       1.00      0.86      0.92        57\n",
      "\n",
      "    accuracy                           0.92       105\n",
      "   macro avg       0.93      0.93      0.92       105\n",
      "weighted avg       0.93      0.92      0.92       105\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\ProgramData\\anaconda3\\Lib\\site-packages\\sklearn\\linear_model\\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):\n",
      "STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.\n",
      "\n",
      "Increase the number of iterations (max_iter) or scale the data as shown in:\n",
      "    https://scikit-learn.org/stable/modules/preprocessing.html\n",
      "Please also refer to the documentation for alternative solver options:\n",
      "    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression\n",
      "  n_iter_i = _check_optimize_result(\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.metrics import accuracy_score, classification_report\n",
    "import urllib.parse\n",
    "import pickle\n",
    "\n",
    "# Load dataset\n",
    "http = pd.read_csv(r'C:\\Users\\Rudra kumar\\Desktop\\`\\project\\Python proj\\New folder (2)\\all_datas_f.csv')\n",
    "missing_values = http.isna().sum()\n",
    "print(missing_values)\n",
    "\n",
    "# Check if the necessary columns exist\n",
    "required_columns = ['path', 'body', 'class']\n",
    "missing_columns = [col for col in required_columns if col not in http.columns]\n",
    "\n",
    "if missing_columns:\n",
    "    raise ValueError(f\"Error: The dataset is missing the following columns: {', '.join(missing_columns)}\")\n",
    "\n",
    "\n",
    "\n",
    "badwords = ['sleep', 'uid', 'select', 'waitfor', 'delay', 'system', 'union', 'order by', 'group by', 'admin', 'drop', 'script']\n",
    "\n",
    "\n",
    "http['features'] = http.apply(lambda row: ExtractFeatures(row['path'], row['body']), axis=1)\n",
    "\n",
    "X = np.array(http['features'].tolist())\n",
    "y = http['class'].values\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "\n",
    "model = LogisticRegression(random_state=42)\n",
    "model.fit(X_train, y_train)\n",
    "\n",
    "filename = 'finalized_model.pkl'\n",
    "pickle.dump(model, open(filename, 'wb'))\n",
    "\n",
    "\n",
    "y_pred = model.predict(X_test)\n",
    "\n",
    "# Evaluate the model\n",
    "print(\"Accuracy:\", accuracy_score(y_test, y_pred))\n",
    "print(\"Classification Report:\")\n",
    "print(classification_report(y_test, y_pred))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55f29cc5-1588-431b-87f8-aed849ce7c6e",
   "metadata": {},
   "outputs": [],
   "source": [
    "http['prediction'] = model.predict(X)\n",
    "\n",
    "   \n",
    "#http.to_csv(r'C:\\Users\\Rudra kumar\\Desktop\\Python proj\\predicted_data2.csv', index=False)\n",
    "print(\"Predicted data saved to predicted_data.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ba976a97-9b85-440e-bdf9-13d54b0d60a0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Predictions saved to testing_datas_with_predictions.csv\n"
     ]
    }
   ],
   "source": [
    "testing_data = pd.read_csv(r'C:\\Users\\Rudra kumar\\Desktop\\`\\project\\Python proj\\New folder (2)\\new_data.csv')\n",
    "if 'path' in testing_data.columns and 'body' in testing_data.columns:\n",
    "        # Extract features from the testing data paths and bodies\n",
    "    test_features = testing_data.apply(lambda row: ExtractFeatures(row['path'], row['body']), axis=1).tolist()\n",
    "\n",
    "        # Convert test_features to a 2D numpy array\n",
    "    test_features = np.array(test_features)\n",
    "\n",
    "        # Predict whether each data point is good or bad\n",
    "    predictions = model.predict(test_features)\n",
    "\n",
    "        # Add the predictions to the testing data DataFrame\n",
    "    testing_data['Prediction'] = predictions\n",
    "\n",
    "        # Save the testing data with predictions to a new CSV file\n",
    "    #testing_data.to_csv(r'C:\\Users\\Rudra kumar\\Desktop\\Python proj\\testing_datas_with_predictions2.csv', index=False)\n",
    "    print(\"Predictions saved to testing_datas_with_predictions.csv\")\n",
    "else:\n",
    "    print(\"Error: The testing data must contain 'path' and 'body' columns.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "57c14758-a703-4e03-ac5d-bb1b0d4cf629",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAA04AAAIjCAYAAAA0vUuxAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjcuNSwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/xnp5ZAAAACXBIWXMAAA9hAAAPYQGoP6dpAABJl0lEQVR4nO3deXQUVd7G8aezB7KxZBMCQQUB2UYQJiqLEomiDIgeHUAJqKgICCKj8KqgI2MUlwEEYWSGZRwRVJZRRBQjQZCIyjYOSwQNOwmbJKwJSd/3j0xa24RUN1m6Q76fc+pAbt2q/nX1JclDVd2yGWOMAAAAAAAX5OPpAgAAAADA2xGcAAAAAMACwQkAAAAALBCcAAAAAMACwQkAAAAALBCcAAAAAMACwQkAAAAALBCcAAAAAMACwQkAAAAALBCcAKAGio+P16BBgxxfp6WlyWazKS0trcJew2az6bnnnquw/XnK22+/rebNm8vf318RERFub797927ZbDa9+uqrFV+clxg0aJDi4+Mvattu3bqpW7duFVoPAFQGghMAVLG5c+fKZrM5lqCgIDVr1kzDhw9Xdna2p8tzy/Llyy+JcHQhO3bs0KBBg3TFFVdo1qxZeuutty7Y1xuORfGYevDBB0td//TTTzv6HD16tIqrA4Dqzc/TBQBATfXnP/9ZTZo00blz57R27VrNmDFDy5cv13//+1/VqlWrSmvp0qWLzp49q4CAALe2W758uaZPn15qYDh79qz8/Kr3j5m0tDTZ7XZNmTJFV155ZZl9yzoWVSkoKEiLFi3Sm2++WeLzfPfddxUUFKRz5855qDoAqL444wQAHnLrrbfq3nvv1YMPPqi5c+dq1KhRyszM1L///e8LbnP69OlKqcXHx0dBQUHy8am4HwtBQUHVPjgdPnxYki7qEj1PueWWW5Sbm6tPPvnEqX3dunXKzMzUbbfd5qHKAKB6IzgBgJe46aabJEmZmZmSiu4bCQkJ0Y8//qiePXsqNDRUAwYMkCTZ7XZNnjxZV199tYKCghQdHa2HH35YP//8s9M+jTGaOHGiGjZsqFq1aunGG2/U1q1bS7z2he5xWr9+vXr27Kk6deqodu3aatOmjaZMmeKob/r06ZLkdOlhsdLucdq0aZNuvfVWhYWFKSQkRN27d9fXX3/t1Kf4UsavvvpKo0ePVmRkpGrXrq077rhDR44ccer73XffKSkpSfXr11dwcLCaNGmi+++/35XDrTfffFNXX321AgMDddlll2nYsGE6ceKEY318fLwmTJggSYqMjCzzni2rY1Hsrbfe0hVXXKHAwEBde+21+vbbb0v02bFjh+666y7VrVtXQUFB6tChgz788EOX3pMkNWjQQF26dNH8+fOd2t955x21bt1arVq1KnW7999/X+3bt1dwcLDq16+ve++9VwcOHCjRb+nSpWrVqpWCgoLUqlUrLVmypNT9uTpGAaC6qN7/FQgAl5Aff/xRklSvXj1HW0FBgZKSknTDDTfo1VdfdVzC9/DDD2vu3LkaPHiwHnvsMWVmZmratGnatGmTvvrqK/n7+0uSxo8fr4kTJ6pnz57q2bOnNm7cqB49eig/P9+ynpUrV+r2229XbGysRo4cqZiYGG3fvl3Lli3TyJEj9fDDD+vgwYNauXKl3n77bcv9bd26VZ07d1ZYWJiefPJJ+fv7629/+5u6deum1atXq1OnTk79R4wYoTp16mjChAnavXu3Jk+erOHDh2vhwoWSis4G9ejRQ5GRkRo7dqwiIiK0e/duLV682LKW5557Ts8//7wSExM1dOhQZWRkaMaMGfr2228dx2/y5Mn65z//qSVLlmjGjBkKCQlRmzZtSt2fK8di/vz5OnnypB5++GHZbDZNmjRJffv21U8//eT4vLZu3arrr79eDRo00NixY1W7dm2999576tOnjxYtWqQ77rjD8r1JUv/+/TVy5EidOnVKISEhKigo0Pvvv6/Ro0eXeple8Vi69tprlZKSouzsbE2ZMkVfffWVNm3a5Djj9tlnn+nOO+9Uy5YtlZKSomPHjmnw4MFq2LBhqcfElTEKANWGAQBUqTlz5hhJ5vPPPzdHjhwx+/btMwsWLDD16tUzwcHBZv/+/cYYY5KTk40kM3bsWKft16xZYySZd955x6l9xYoVTu2HDx82AQEB5rbbbjN2u93R7//+7/+MJJOcnOxoW7VqlZFkVq1aZYwxpqCgwDRp0sQ0btzY/Pzzz06v8+t9DRs2zFzoR4kkM2HCBMfXffr0MQEBAebHH390tB08eNCEhoaaLl26lDg+iYmJTq/1+OOPG19fX3PixAljjDFLliwxksy3335b6utfSPFx6dGjhyksLHS0T5s2zUgys2fPdrRNmDDBSDJHjhyx3O+FjkVmZqaRZOrVq2eOHz/uaP/3v/9tJJmPPvrI0da9e3fTunVrc+7cOUeb3W431113nWnatKllDZLMsGHDzPHjx01AQIB5++23jTHGfPzxx8Zms5ndu3eXeE/5+fkmKirKtGrVypw9e9axr2XLlhlJZvz48Y62du3amdjYWMdnYIwxn332mZFkGjdu7GhzdYwaY0zXrl1N165dLd8bAHgal+oBgIckJiYqMjJScXFx+uMf/6iQkBAtWbJEDRo0cOo3dOhQp6/ff/99hYeH6+abb9bRo0cdS/v27RUSEqJVq1ZJkj7//HPl5+drxIgRTpeNjRo1yrK2TZs2KTMzU6NGjSpxf09pl6BZKSws1GeffaY+ffro8ssvd7THxsaqf//+Wrt2rXJzc522eeihh5xeq3PnziosLNSePXsk/XLf0bJly3T+/HmXayk+LqNGjXK6p2vIkCEKCwvTxx9/7Pb7c8U999yjOnXqOL7u3LmzJOmnn36SJB0/flxffPGF7r77bp08edLxuR47dkxJSUnauXNnqZfOlaZOnTq65ZZb9O6770oqOtt13XXXqXHjxiX6fvfddzp8+LAeffRRBQUFOdpvu+02NW/e3HE8Dh06pM2bNys5OVnh4eGOfjfffLNatmzptE9XxygAVCdcqgcAHjJ9+nQ1a9ZMfn5+io6O1lVXXVVicgY/P78Sl0Ht3LlTOTk5ioqKKnW/xRMaFAeMpk2bOq2PjIx0+gW+NMWXDV7ofhh3HTlyRGfOnNFVV11VYl2LFi1kt9u1b98+XX311Y72Ro0aOfUrrrn4HpmuXbvqzjvv1PPPP6+//vWv6tatm/r06aP+/fsrMDDwgrUUH5ff1hIQEKDLL7/csb6iWb2fXbt2yRijZ599Vs8++2yp+zh8+HCJYH0h/fv313333ae9e/dq6dKlmjRpUqn9LnQ8JKl58+Zau3atU7/fjqfibTdu3Oj42tUxCgDVCcEJADykY8eO6tChQ5l9AgMDS4Qpu92uqKgovfPOO6VuExkZWWE1epKvr2+p7cYYSUVnvj744AN9/fXX+uijj/Tpp5/q/vvv12uvvaavv/5aISEhVVmuJav3Y7fbJUljxoxRUlJSqX2tpkT/tT/84Q8KDAxUcnKy8vLydPfdd7tZ8cWrKWMUQM1CcAKAauaKK67Q559/ruuvv17BwcEX7Fd8WdbOnTudLo87cuSI5cxmV1xxhSTpv//9rxITEy/Yz9XL9iIjI1WrVi1lZGSUWLdjxw75+PgoLi7OpX391u9//3v9/ve/11/+8hfNnz9fAwYM0IIFCy74ENji45KRkeF0XPLz85WZmVnm+y3LxVzC+GvFtfj7+190Db8WHBysPn366F//+pduvfVW1a9fv9R+vz4exTM7FsvIyHCs//V4+q3ffq6ujlEAqE64xwkAqpm7775bhYWFeuGFF0qsKygocEypnZiYKH9/f73xxhuOsxqSNHnyZMvXuOaaa9SkSRNNnjzZaYpuSU77ql27tiSV6PNbvr6+6tGjh/79739r9+7djvbs7GzNnz9fN9xwg8LCwizr+rWff/7ZqRZJateunSQpLy/vgtslJiYqICBAU6dOddr+H//4h3Jyci76OUeuHosLiYqKUrdu3fS3v/1Nhw4dKrH+t1Oxu2LMmDGaMGHCBS/9k6QOHTooKipKM2fOdDpun3zyibZv3+44HrGxsWrXrp3mzZunnJwcR7+VK1dq27ZtTvt0dYwCQHXCGScAqGa6du2qhx9+WCkpKdq8ebN69Oghf39/7dy5U++//76mTJmiu+66S5GRkRozZoxSUlJ0++23q2fPntq0aZM++eSTC559KObj46MZM2aoV69eateunQYPHqzY2Fjt2LFDW7du1aeffipJat++vSTpscceU1JSknx9ffXHP/6x1H1OnDhRK1eu1A033KBHH31Ufn5++tvf/qa8vLwL3n9Tlnnz5unNN9/UHXfcoSuuuEInT57UrFmzFBYWpp49e15wu8jISI0bN07PP/+8brnlFv3hD39QRkaG3nzzTV177bW699573a5Fcu9YXMj06dN1ww03qHXr1hoyZIguv/xyZWdnKz09Xfv379eWLVvc2l/btm3Vtm3bMvv4+/vr5Zdf1uDBg9W1a1f169fPMR15fHy8Hn/8cUfflJQU3Xbbbbrhhht0//336/jx43rjjTd09dVX69SpU45+ro5RAKhWPDijHwDUSMXTbVtNo52cnGxq1659wfVvvfWWad++vQkODjahoaGmdevW5sknnzQHDx509CksLDTPP/+8iY2NNcHBwaZbt27mv//9r2ncuHGZ05EXW7t2rbn55ptNaGioqV27tmnTpo154403HOsLCgrMiBEjTGRkpLHZbE7Tces305EbY8zGjRtNUlKSCQkJMbVq1TI33nijWbdunUvH57c1bty40fTr1880atTIBAYGmqioKHP77beb7777rqzD6jBt2jTTvHlz4+/vb6Kjo83QoUNLTL3uznTkFzoWxdORv/LKKyW2Ke0Y/fjjj2bgwIEmJibG+Pv7mwYNGpjbb7/dfPDBB5Y16H/TkZflQu9p4cKF5ne/+50JDAw0devWNQMGDHBMjf9rixYtMi1atDCBgYGmZcuWZvHixSY5OdlpOvJiroxRpiMHUF3YjPnNdQ4AAAAAACfc4wQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGChxj0A12636+DBgwoNDZXNZvN0OQAAAAA8xBijkydP6rLLLpOPT9nnlGpccDp48KDi4uI8XQYAAAAAL7Fv3z41bNiwzD41LjiFhoZKKjo4YWFhHq4GAAAAgKfk5uYqLi7OkRHKUuOCU/HleWFhYQQnAAAAAC7dwsPkEAAAAABggeAEAAAAABYITgAAAABgocbd4wQAKKmwsFDnz5/3dBmoAr6+vvLz8+ORHADgJoITANRwp06d0v79+2WM8XQpqCK1atVSbGysAgICPF0KAFQbBCcAqMEKCwu1f/9+1apVS5GRkZyFuMQZY5Sfn68jR44oMzNTTZs2tXzgIwCgCMEJAGqw8+fPyxijyMhIBQcHe7ocVIHg4GD5+/trz549ys/PV1BQkKdLAoBqgf9mAgBwpqmG4SwTALiP75wAAAAAYIHgBAAAAAAWCE4AgHIrLJTS0qR33y36s7DQ0xVVjEGDBqlPnz6Or7t166ZRo0aVa58VsQ8AQNUjOAEAymXxYik+XrrxRql//6I/4+OL2ivLoEGDZLPZZLPZFBAQoCuvvFJ//vOfVVBQUHkvKmnx4sV64YUXXOqblpYmm82mEydOXPQ+AADeg+AEALhoixdLd90l7d/v3H7gQFF7ZYanW265RYcOHdLOnTv1xBNP6LnnntMrr7xSol9+fn6FvWbdunUVGhrq8X0AAKoe05GjWikslNaskQ4dkmJjpc6dJV/fqtse8CaeHs+FhdLIkVJpz801RrLZpFGjpN69K6euwMBAxcTESJKGDh2qJUuW6MMPP1RGRoZOnDiha6+9VtOnT1dgYKAyMzO1b98+PfHEE/rss8/k4+Ojzp07a8qUKYqPj//f+ynUn/70J82ePVu+vr564IEHSjwUuFu3bmrXrp0mT54sScrLy9P48eM1f/58HT58WHFxcRo3bpy6d++uG2+8UZJUp04dSVJycrLmzp1bYh8///yzRo4cqY8++kh5eXnq2rWrpk6dqqZNm0qS5s6dq1GjRmnhwoUaNWqU9u3bpxtuuEFz5sxRbGyspKKzW08++aS2bt0qf39/XX311Zo/f74aN25c8QfeCxSP/QMHpCNHpHr1iv48dqxofd26UkxM0SJJWVlSdrbz+qgo520iIqTik4MXs96btynPPn18pG7dir6/rFlTdCmu3e7a67j7Gbha+7FjUmRk6fv28fnle2FWVunjw1s+l+o8Di9mn78dE4cPV7/fxTwanL788ku98sor2rBhgw4dOqQlS5Y4XUtemrS0NI0ePVpbt25VXFycnnnmGQ0aNKhK6oVnLV5c9Evar/9nu2FDacoUqW/fyt8e8CbeMJ7XrCl5punXjJH27Svq161b5dcTHBysY//7CZ2amqqwsDCtXLlSUtHzqpKSkpSQkKA1a9bIz89PEydO1C233KL//Oc/CggI0Guvvaa5c+dq9uzZatGihV577TUtWbJEN9100wVfc+DAgUpPT9fUqVPVtm1bZWZm6ujRo4qLi9OiRYt05513KiMjQ2FhYRd8TtagQYO0c+dOffjhhwoLC9NTTz2lnj17atu2bfL395cknTlzRq+++qrefvtt+fj46N5779WYMWP0zjvvqKCgQH369NGQIUP07rvvKj8/X998880lO8V8aWMflWvixKL/CCntP0mA8qpWv4sZD1q+fLl5+umnzeLFi40ks2TJkjL7//TTT6ZWrVpm9OjRZtu2beaNN94wvr6+ZsWKFS6/Zk5OjpFkcnJyylk9qtKiRcbYbMYUfdv+ZbHZipZFiyp3e8CbVOR4Pnv2rNm2bZs5e/as23XMn1+yhtKW+fPd3rWl5ORk07t3b2OMMXa73axcudIEBgaaMWPGmOTkZBMdHW3y8vIc/d9++21z1VVXGbvd7mjLy8szwcHB5tNPPzXGGBMbG2smTZrkWH/+/HnTsGFDx+sYY0zXrl3NyJEjjTHGZGRkGElm5cqVpda4atUqI8n8/PPPTu2/3scPP/xgJJmvvvrKsf7o0aMmODjYvPfee8YYY+bMmWMkmV27djn6TJ8+3URHRxtjjDl27JiRZNLS0lw4ckXK87l70oXGPgsLS/VdPP27mDvZwKP3ON16662aOHGi7rjjDpf6z5w5U02aNNFrr72mFi1aaPjw4brrrrv017/+tZIrhSdZXQ4kFV0OdKFZvMq7PeBNvGk8/+8qsQrr565ly5YpJCREQUFBuvXWW3XPPffoueeekyS1bt1aAQEBjr5btmzRrl27FBoaqpCQEIWEhKhu3bo6d+6cfvzxR+Xk5OjQoUPq1KmTYxs/Pz916NDhgq+/efNm+fr6qmvXrhf9HrZv3y4/Pz+n161Xr56uuuoqbd++3dFWq1YtXXHFFY6vY2NjdfjwYUlF90wNGjRISUlJ6tWrl6ZMmaJDhw5ddE3eqqyxD6D6qk6/i1WrySHS09OVmJjo1JaUlKT09PQLbpOXl6fc3FynBdWLO5cDVcb2gDfxpvHcuXPRJRYXuiLMZpPi4or6VYYbb7xRmzdv1s6dO3X27FnNmzdPtWvXliTHn8VOnTql9u3ba/PmzU7LDz/8oP79+1/U61/o0rvKUHzJXjGbzSbzqwQxZ84cpaen67rrrtPChQvVrFkzff3111VWX1WwGvsAqq/q8rtYtQpOWVlZio6OdmqLjo5Wbm6uzp49W+o2KSkpCg8PdyxxcXFVUSoqkKv/cXqhfuXdHvAm3jSefX2LrkuXSoan4q8nT668m35r166tK6+8Uo0aNZKfX9m37F5zzTXauXOnoqKidOWVVzotxT8fYmNjtX79esc2BQUF2rBhwwX32bp1a9ntdq1evbrU9cVnvArL+C/UFi1aqKCgwOl1jx07poyMDLVs2bLM9/Rbv/vd7zRu3DitW7dOrVq10vz5893a3tvxPRq49Hn7v/NqFZwuxrhx45STk+NY9u3b5+mS4KbyXg7k6cuJgIrkbeO5b1/pgw+kBg2c2xs2LGr3lpt9BwwYoPr166t3795as2aNMjMzlZaWpscee0z7/3caY+TIkXrppZe0dOlS7dixQ48++miJZzD9Wnx8vJKTk3X//fdr6dKljn2+9957kqTGjRvLZrNp2bJlOnLkiE6dOlViH02bNlXv3r01ZMgQrV27Vlu2bNG9996rBg0aqHfv3i69t8zMTI0bN07p6enas2ePPvvsM+3cuVMtWrRw/0B5Mb5HA5c+b/93Xq2CU0xMjLKzs53asrOzy5ytKDAwUGFhYU4LqpfyXg7k6cuJgIrkjeO5b19p925p1Spp/vyiPzMzvSc0SUX3CH355Zdq1KiR+vbtqxYtWuiBBx7QuXPnHD8XnnjiCd13331KTk5WQkKCQkNDLe/BnTFjhu666y49+uijat68uYYMGaLTp09Lkho0aKDnn39eY8eOVXR0tIYPH17qPubMmaP27dvr9ttvV0JCgowxWr58eYnL88p6bzt27NCdd96pZs2a6aGHHtKwYcP08MMPu3GEvF/x2Adw6akuv4vZjPGO2yxtNpvldORPPfWUli9fru+//97R1r9/fx0/flwrVqxw6XVyc3MVHh6unJwcQlQ1UvyQTcn5xuDiXx6t/me7vNsD3qQix/O5c+eUmZmpJk2aKCgoqGILhdeqrp978dj3jt9cAFQET/8u5k428OgZp1OnTjlu0JWKLjfYvHmz9u7dK6noMruBAwc6+j/yyCP66aef9OSTT2rHjh1688039d577+nxxx/3RPmoQuW9HKi6XE4EuILxjJqqeOxz5qnqXaKPBYMXqE4/uzx6xiktLc3xZPVfK366+qBBg7R7926lpaU5bfP4449r27ZtatiwoZ599lm3HoDLGafqrfhp8YcOXdzTpsu7PeBNKmI8V9czDyif6v65F4/9AwekI0ekevWK/vzf849Vt64UE1O0SFJWlpSd7bw+Ksp5m4gIqfiWtotZ783blGefPj5FD7Du3LnomKelSXa7a6/j7mfgau3HjkmRkaXv28fnl++FWVmljw9v+Vyq8zi8mH3+dkwcPuwdv4u5kw285lK9qkJwAoBfVPdfoHFx+NwBoEi1uVQPAAAAAKoDghMAQDXs4oMaj88bANxHcAKAGsz3fxeW5+fne7gSVKUzZ85IkstTngMApLIftQ4AuKT5+fmpVq1aOnLkiPz9/eXjw/+nXcqMMTpz5owOHz6siIgIR3AGAFgjOAFADWaz2RQbG6vMzEzt2bPH0+WgikRERCimeGorAIBLCE4AUMMFBASoadOmXK5XQ/j7+3OmCQAuAsEJACAfHx+mpQYAoAxczA4AAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGDB48Fp+vTpio+PV1BQkDp16qRvvvmmzP6TJ0/WVVddpeDgYMXFxenxxx/XuXPnqqhaAAAAADWRR4PTwoULNXr0aE2YMEEbN25U27ZtlZSUpMOHD5faf/78+Ro7dqwmTJig7du36x//+IcWLlyo//u//6viygEAAADUJB4NTq+//rqGDBmiwYMHq2XLlpo5c6Zq1aql2bNnl9p/3bp1uv7669W/f3/Fx8erR48e6tevn+VZKgAAAAAoD48Fp/z8fG3YsEGJiYm/FOPjo8TERKWnp5e6zXXXXacNGzY4gtJPP/2k5cuXq2fPnhd8nby8POXm5jotAAAAAOAOP0+98NGjR1VYWKjo6Gin9ujoaO3YsaPUbfr376+jR4/qhhtukDFGBQUFeuSRR8q8VC8lJUXPP/98hdYOAAAAoGbx+OQQ7khLS9OLL76oN998Uxs3btTixYv18ccf64UXXrjgNuPGjVNOTo5j2bdvXxVWDAAAAOBS4LEzTvXr15evr6+ys7Od2rOzsxUTE1PqNs8++6zuu+8+Pfjgg5Kk1q1b6/Tp03rooYf09NNPy8enZA4MDAxUYGBgxb8BAAAAADWGx844BQQEqH379kpNTXW02e12paamKiEhodRtzpw5UyIc+fr6SpKMMZVXLAAAAIAazWNnnCRp9OjRSk5OVocOHdSxY0dNnjxZp0+f1uDBgyVJAwcOVIMGDZSSkiJJ6tWrl15//XX97ne/U6dOnbRr1y49++yz6tWrlyNAAQAAAEBF82hwuueee3TkyBGNHz9eWVlZateunVasWOGYMGLv3r1OZ5ieeeYZ2Ww2PfPMMzpw4IAiIyPVq1cv/eUvf/HUWwAAAABQA9hMDbvGLTc3V+Hh4crJyVFYWJinywEAAADgIe5kg2o1qx4AAAAAeALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwIKfK51yc3Nd3mFYWNhFFwMAAAAA3sil4BQRESGbzVZmH2OMbDabCgsLK6QwAAAAAPAWLgWnVatWVXYdAAAAAOC1XApOXbt2rew6AAAAAMBrXdTkEGvWrNG9996r6667TgcOHJAkvf3221q7dm2FFgcAAAAA3sDt4LRo0SIlJSUpODhYGzduVF5eniQpJydHL774YoUXCAAAAACe5nZwmjhxombOnKlZs2bJ39/f0X799ddr48aNbhcwffp0xcfHKygoSJ06ddI333xTZv8TJ05o2LBhio2NVWBgoJo1a6bly5e7/boAAAAA4CqX7nH6tYyMDHXp0qVEe3h4uE6cOOHWvhYuXKjRo0dr5syZ6tSpkyZPnqykpCRlZGQoKiqqRP/8/HzdfPPNioqK0gcffKAGDRpoz549ioiIcPdtAAAAAIDL3A5OMTEx2rVrl+Lj453a165dq8svv9ytfb3++usaMmSIBg8eLEmaOXOmPv74Y82ePVtjx44t0X/27Nk6fvy41q1b5zjb9ds6AAAAAKCiuX2p3pAhQzRy5EitX79eNptNBw8e1DvvvKMxY8Zo6NChLu8nPz9fGzZsUGJi4i/F+PgoMTFR6enppW7z4YcfKiEhQcOGDVN0dLRatWqlF198scxnR+Xl5Sk3N9dpAQAAAAB3uH3GaezYsbLb7erevbvOnDmjLl26KDAwUGPGjNGIESNc3s/Ro0dVWFio6Ohop/bo6Gjt2LGj1G1++uknffHFFxowYICWL1+uXbt26dFHH9X58+c1YcKEUrdJSUnR888/7/obBAAAAIDfsBljzMVsmJ+fr127dunUqVNq2bKlQkJC3Nr+4MGDatCggdatW6eEhARH+5NPPqnVq1dr/fr1JbZp1qyZzp07p8zMTPn6+koqutzvlVde0aFDh0p9nby8PMfMf5KUm5uruLg45eTkKCwszK2aAQAAAFw6cnNzFR4e7lI2cPuMU7GAgACFhoYqNDTU7dAkSfXr15evr6+ys7Od2rOzsxUTE1PqNrGxsfL393eEJklq0aKFsrKylJ+fr4CAgBLbBAYGKjAw0O36AAAAAKCY2/c4FRQU6Nlnn1V4eLji4+MVHx+v8PBwPfPMMzp//rzL+wkICFD79u2VmprqaLPb7UpNTXU6A/Vr119/vXbt2iW73e5o++GHHxQbG1tqaAIAAACAiuB2cBoxYoTeeustTZo0SZs2bdKmTZs0adIk/eMf/9Bjjz3m1r5Gjx6tWbNmad68edq+fbuGDh2q06dPO2bZGzhwoMaNG+foP3ToUB0/flwjR47UDz/8oI8//lgvvviihg0b5u7bAAAAAACXuX2p3vz587VgwQLdeuutjrY2bdooLi5O/fr104wZM1ze1z333KMjR45o/PjxysrKUrt27bRixQrHhBF79+6Vj88v2S4uLk6ffvqpHn/8cbVp00YNGjTQyJEj9dRTT7n7NgAAAADAZW5PDhEVFaXVq1erRYsWTu3bt29Xly5ddOTIkQotsKK5cwMYAAAAgEuXO9nA7Uv1hg8frhdeeMFpprq8vDz95S9/0fDhw92vFgAAAAC8nEuX6vXt29fp688//1wNGzZU27ZtJUlbtmxRfn6+unfvXvEVAgAAAICHuRScwsPDnb6+8847nb6Oi4uruIoAAAAAwMu4FJzmzJlT2XUAAAAAgNdy+x4nAAAAAKhp3J6OXJI++OADvffee9q7d6/y8/Od1m3cuLFCCgMAAAAAb+H2GaepU6dq8ODBio6O1qZNm9SxY0fVq1dPP/30k9OznQAAAADgUuF2cHrzzTf11ltv6Y033lBAQICefPJJrVy5Uo899phycnIqo0YAAAAA8Ci3g9PevXt13XXXSZKCg4N18uRJSdJ9992nd999t2KrAwAAAAAv4HZwiomJ0fHjxyVJjRo10tdffy1JyszMlDGmYqsDAAAAAC/gdnC66aab9OGHH0qSBg8erMcff1w333yz7rnnHt1xxx0VXiAAAAAAeJrNuHmayG63y263y8+vaEK+BQsWaN26dWratKkeeeQR+fv7V0qhFSU3N1fh4eHKyclRWFiYp8sBAAAA4CHuZAO3g9OFnDhxQsuXL1f//v0rYneVhuAEAAAAQHIvG1TYA3D37Nmj++67r6J2BwAAAABeo8KCEwAAAABcqghOAAAAAGCB4AQAAAAAFvxc7Th16tQy1x84cKDcxQAAAACAN3I5OP31r3+17NOoUaNyFQMAAAAA3sjl4JSZmVmZdQAAAACA1+IeJwAAAACwQHACAAAAAAsEJwAAAACwQHACAAAAAAsEJwAAAACw4NKserm5uS7vMCws7KKLAQAAAABv5FJwioiIkM1mc2mHhYWF5SoIAAAAALyNS8Fp1apVjr/v3r1bY8eO1aBBg5SQkCBJSk9P17x585SSklI5VQIAAACAB9mMMcadDbp3764HH3xQ/fr1c2qfP3++3nrrLaWlpVVkfRUuNzdX4eHhysnJ4bJCAAAAoAZzJxu4PTlEenq6OnToUKK9Q4cO+uabb9zdHQAAAAB4PbeDU1xcnGbNmlWi/e9//7vi4uIqpCgAAAAA8CYu3eP0a3/9619155136pNPPlGnTp0kSd9884127typRYsWVXiBAAAAAOBpbp9x6tmzp3744Qf16tVLx48f1/Hjx9WrVy/98MMP6tmzZ2XUCAAAAAAe5fbkENUdk0MAAAAAkCp5cghJWrNmje69915dd911OnDggCTp7bff1tq1ay9mdwAAAADg1dwOTosWLVJSUpKCg4O1ceNG5eXlSZJycnL04osvVniBAAAAAOBpbgeniRMnaubMmZo1a5b8/f0d7ddff702btxYocUBAAAAgDdwOzhlZGSoS5cuJdrDw8N14sSJiqgJAAAAALyK28EpJiZGu3btKtG+du1aXX755RVSFAAAAAB4E7eD05AhQzRy5EitX79eNptNBw8e1DvvvKMxY8Zo6NChlVEjAAAAAHiU2w/AHTt2rOx2u7p3764zZ86oS5cuCgwM1JgxYzRixIjKqBEAAAAAPOqin+OUn5+vXbt26dSpU2rZsqVCQkIqurZKwXOcAAAAAEiV/Byn+++/XydPnlRAQIBatmypjh07KiQkRKdPn9b9999/0UUDAAAAgLdyOzjNmzdPZ8+eLdF+9uxZ/fOf/6yQogAAAADAm7h8j1Nubq6MMTLG6OTJkwoKCnKsKyws1PLlyxUVFVUpRQIAAACAJ7kcnCIiImSz2WSz2dSsWbMS6202m55//vkKLQ4AAAAAvIHLwWnVqlUyxuimm27SokWLVLduXce6gIAANW7cWJdddlmlFAkAAAAAnuRycOrataskKTMzU40aNZLNZqu0ogAAAADAm7g9OcQXX3yhDz74oET7+++/r3nz5lVIUQAAAADgTdwOTikpKapfv36J9qioKL344osVUhQAAAAAeBO3g9PevXvVpEmTEu2NGzfW3r17K6QoAAAAAPAmbgenqKgo/ec//ynRvmXLFtWrV69CigIAAAAAb+J2cOrXr58ee+wxrVq1SoWFhSosLNQXX3yhkSNH6o9//GNl1AgAAAAAHuXyrHrFXnjhBe3evVvdu3eXn1/R5na7XQMHDuQeJwAAAACXJJsxxlzMhj/88IO2bNmi4OBgtW7dWo0bN67o2ipFbm6uwsPDlZOTo7CwME+XAwAAAMBD3MkGbp9xKtasWTM1a9bsYjcHAAAAgGrDpeA0evRovfDCC6pdu7ZGjx5dZt/XX3+9QgoDAAAAAG/hUnDatGmTzp8/7/j7hdhstoqpCgAAAAC8yEXf41RdcY8TAAAAAMm9bOD2dOQAAAAAUNO4dKle3759Xd7h4sWLL7oYAAAAAPBGLp1xCg8PdyxhYWFKTU3Vd99951i/YcMGpaamKjw8vNIKBQAAAABPcemM05w5cxx/f+qpp3T33Xdr5syZ8vX1lSQVFhbq0Ucf5Z4hAAAAAJcktyeHiIyM1Nq1a3XVVVc5tWdkZOi6667TsWPHKrTAisbkEAAAAACkSp4coqCgQDt27CjRvmPHDtntdnd3BwAAAABez6VL9X5t8ODBeuCBB/Tjjz+qY8eOkqT169frpZde0uDBgyu8QAAAAADwNLeD06uvvqqYmBi99tprOnTokCQpNjZWf/rTn/TEE09UeIEAAAAA4GnlegBubm6uJFWre4W4xwkAAACAVAUPwC0oKNDnn3+ud999VzabTZJ08OBBnTp16mJ2BwAAAABeze1L9fbs2aNbbrlFe/fuVV5enm6++WaFhobq5ZdfVl5enmbOnFkZdQIAAACAx7h9xmnkyJHq0KGDfv75ZwUHBzva77jjDqWmplZocQAAAADgDdw+47RmzRqtW7dOAQEBTu3x8fE6cOBAhRUGAAAAAN7C7TNOdrtdhYWFJdr379+v0NDQCikKAAAAALyJ28GpR48emjx5suNrm82mU6dOacKECerZs+dFFTF9+nTFx8crKChInTp10jfffOPSdgsWLJDNZlOfPn0u6nUBAAAAwBVuB6dXX31VX331lVq2bKlz586pf//+jsv0Xn75ZbcLWLhwoUaPHq0JEyZo48aNatu2rZKSknT48OEyt9u9e7fGjBmjzp07u/2aAAAAAOCOi3qOU0FBgRYuXKgtW7bo1KlTuuaaazRgwACnySJc1alTJ1177bWaNm2apKJLAePi4jRixAiNHTu21G0KCwvVpUsX3X///VqzZo1OnDihpUuXuvR6PMcJAAAAgOReNnBrcojz58+refPmWrZsmQYMGKABAwaUq9D8/Hxt2LBB48aNc7T5+PgoMTFR6enpF9zuz3/+s6KiovTAAw9ozZo1Zb5GXl6e8vLyHF8XP7QXAAAAAFzl1qV6/v7+OnfuXIW9+NGjR1VYWKjo6Gin9ujoaGVlZZW6zdq1a/WPf/xDs2bNcuk1UlJSFB4e7lji4uLKXTcAAACAmsXte5yGDRuml19+WQUFBZVRT5lOnjyp++67T7NmzVL9+vVd2mbcuHHKyclxLPv27avkKgEAAABcatx+jtO3336r1NRUffbZZ2rdurVq167ttH7x4sUu76t+/fry9fVVdna2U3t2drZiYmJK9P/xxx+1e/du9erVy9Fmt9slSX5+fsrIyNAVV1zhtE1gYKACAwNdrgkAAAAAfsvt4BQREaE777yzQl48ICBA7du3V2pqqmNKcbvdrtTUVA0fPrxE/+bNm+v77793anvmmWd08uRJTZkyhcvwAAAAAFQKt4PTnDlzKrSA0aNHKzk5WR06dFDHjh01efJknT59WoMHD5YkDRw4UA0aNFBKSoqCgoLUqlUrp+0jIiIkqUQ7AAAAAFQUl4OT3W7XK6+8og8//FD5+fnq3r27JkyYcFFTkP/aPffcoyNHjmj8+PHKyspSu3bttGLFCseEEXv37pWPj9u3YgEAAABAhXH5OU4vvPCCnnvuOSUmJio4OFiffvqp+vXrp9mzZ1d2jRWK5zgBAAAAkNzLBi6fyvnnP/+pN998U59++qmWLl2qjz76SO+8845jcgYAAAAAuFS5HJz27t2rnj17Or5OTEyUzWbTwYMHK6UwAAAAAPAWLgengoICBQUFObX5+/vr/PnzFV4UAAAAAHgTlyeHMMZo0KBBTs9EOnfunB555BGnZzm58xwnAAAAAKgOXA5OycnJJdruvffeCi0GAAAAALyRy8Gpop/fBAAAAADVBQ9IAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALXhGcpk+frvj4eAUFBalTp0765ptvLth31qxZ6ty5s+rUqaM6deooMTGxzP4AAAAAUF4eD04LFy7U6NGjNWHCBG3cuFFt27ZVUlKSDh8+XGr/tLQ09evXT6tWrVJ6erri4uLUo0cPHThwoIorBwAAAFBT2IwxxpMFdOrUSddee62mTZsmSbLb7YqLi9OIESM0duxYy+0LCwtVp04dTZs2TQMHDrTsn5ubq/DwcOXk5CgsLKzc9QMAAAContzJBh4945Sfn68NGzYoMTHR0ebj46PExESlp6e7tI8zZ87o/Pnzqlu3bqnr8/LylJub67QAAAAAgDs8GpyOHj2qwsJCRUdHO7VHR0crKyvLpX089dRTuuyyy5zC16+lpKQoPDzcscTFxZW7bgAAAAA1i8fvcSqPl156SQsWLNCSJUsUFBRUap9x48YpJyfHsezbt6+KqwQAAABQ3fl58sXr168vX19fZWdnO7VnZ2crJiamzG1fffVVvfTSS/r888/Vpk2bC/YLDAxUYGBghdQLAAAAoGby6BmngIAAtW/fXqmpqY42u92u1NRUJSQkXHC7SZMm6YUXXtCKFSvUoUOHqigVAAAAQA3m0TNOkjR69GglJyerQ4cO6tixoyZPnqzTp09r8ODBkqSBAweqQYMGSklJkSS9/PLLGj9+vObPn6/4+HjHvVAhISEKCQnx2PsAAAAAcOnyeHC65557dOTIEY0fP15ZWVlq166dVqxY4ZgwYu/evfLx+eXE2IwZM5Sfn6+77rrLaT8TJkzQc889V5WlAwAAAKghPP4cp6rGc5wAAAAASNXoOU4AAAAAUB0QnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAAsEJAAAAACwQnAAAAADAgp+nC6jJCgultLSixW6XIiKkEyeK1tWtK0VFSUeOSMeOFbVZra+qbTxZx7FjUmSkFBNTdPzWrCk6dq7us27dom1jYoq+zsqSsrOr7/Gozp8ldZR/m/L+e7iUj6G31FGda/fmOorHfoMGUufOkq+vnBT/ezh0SIqNLb0PXFOeY1lZn0NZ++Wz916XxGdjvMC0adNM48aNTWBgoOnYsaNZv359mf3fe+89c9VVV5nAwEDTqlUr8/HHH7v8Wjk5OUaSycnJKW/Z5bJokTH16hkjsbCwsLCwsFzs0rBh0c/UX/98bdiw7D5wTXmOZWV9DmXtl8/ee3nzZ+NONlAV1FOmBQsWmICAADN79myzdetWM2TIEBMREWGys7NL7f/VV18ZX19fM2nSJLNt2zbzzDPPGH9/f/P999+79HreEJwWLfL8DxoWFhYWFpZLZbHZfvnF2WYrfX1xH7imPMeysj6HsvZb1tjgs/csb/936U42sBljjCfPeHXq1EnXXnutpk2bJkmy2+2Ki4vTiBEjNHbs2BL977nnHp0+fVrLli1ztP3+979Xu3btNHPmTMvXy83NVXh4uHJychQWFlZxb8RFhYVS48bSgQNV/tIAAFySbLaiy/Ykaf/+C/dp2FDKzKyGlwdVscJCKT7+4o5lebYtT01l4bP3nMoaDxXJnWzg0ckh8vPztWHDBiUmJjrafHx8lJiYqPT09FK3SU9Pd+ovSUlJSRfsn5eXp9zcXKfFk9asITQBAFCRjCn6xaysX6qNkfbtK/o5jLKtWXPxx7I825anprLw2XtOZY0HT/FocDp69KgKCwsVHR3t1B4dHa2srKxSt8nKynKrf0pKisLDwx1LXFxcxRR/kQ4d8ujLAwBQo/Fz2Jqrx6i0fuXZtiL7V9Y+4J7KGg+ecslPRz5u3Djl5OQ4ln379nm0nthYj748AAA1Gj+Hrbl6jErrV55tK7J/Ze0D7qms8eApHg1O9evXl6+vr7Kzs53as7OzFVM8X/RvxMTEuNU/MDBQYWFhTosnde78y3XYAACg/Irvk2jYsOjvF+oTF1f0cxhl69z54o9lebYtT01l4bP3nMoaD57i0eAUEBCg9u3bKzU11dFmt9uVmpqqhISEUrdJSEhw6i9JK1euvGB/b+PrK02d6ukqAAC4tEyZUrRIJX9JK/568mQmB3CFr+/FH8vybFvemir6NVF+lTUePKbS5/izsGDBAhMYGGjmzp1rtm3bZh566CETERFhsrKyjDHG3HfffWbs2LGO/l999ZXx8/Mzr776qtm+fbuZMGFCtZuO3Bie48TCwsLCwlIRS1yc9XOcftsHrinPsaysz6Gs/fLZey9v/myq1XTkkjRt2jS98sorysrKUrt27TR16lR16tRJktStWzfFx8dr7ty5jv7vv/++nnnmGe3evVtNmzbVpEmT1LNnT5dey9PTkf9aYaGUlla02O3V+ynuVVVH8dPiY2J+eQK13e76PuvWLdq2+MrOrCwpO7v6Ho/q/FlSR/m3Ke+/h0v5GHpLHdW5dm+uo3jsN2hQdIlPaVNir1lTdMN5bGzpfeCa8hzLyvocytovn7338tbPxp1s4BXBqSp5U3ACAAAA4DnV5jlOAAAAAFAdEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAsEJwAAAAAwALBCQAAAAAs+Hm6gKpmjJEk5ebmergSAAAAAJ5UnAmKM0JZalxwOnnypCQpLi7Ow5UAAAAA8AYnT55UeHh4mX1sxpV4dQmx2+06ePCgQkNDZbPZPF2OcnNzFRcXp3379iksLMzT5aAGYgzCGzAO4Q0Yh/AGjMOqZYzRyZMnddlll8nHp+y7mGrcGScfHx81bNjQ02WUEBYWxj8OeBRjEN6AcQhvwDiEN2AcVh2rM03FmBwCAAAAACwQnAAAAADAAsHJwwIDAzVhwgQFBgZ6uhTUUIxBeAPGIbwB4xDegHHovWrc5BAAAAAA4C7OOAEAAACABYITAAAAAFggOAEAAACABYITAAAAAFggOHnQ9OnTFR8fr6CgIHXq1EnffPONp0vCJeTLL79Ur169dNlll8lms2np0qVO640xGj9+vGJjYxUcHKzExETt3LnTqc/x48c1YMAAhYWFKSIiQg888IBOnTpVhe8C1VlKSoquvfZahYaGKioqSn369FFGRoZTn3PnzmnYsGGqV6+eQkJCdOeddyo7O9upz969e3XbbbepVq1aioqK0p/+9CcVFBRU5VtBNTZjxgy1adPG8TDRhIQEffLJJ471jEF4wksvvSSbzaZRo0Y52hiL3o/g5CELFy7U6NGjNWHCBG3cuFFt27ZVUlKSDh8+7OnScIk4ffq02rZtq+nTp5e6ftKkSZo6dapmzpyp9evXq3bt2kpKStK5c+ccfQYMGKCtW7dq5cqVWrZsmb788ks99NBDVfUWUM2tXr1aw4YN09dff62VK1fq/Pnz6tGjh06fPu3o8/jjj+ujjz7S+++/r9WrV+vgwYPq27evY31hYaFuu+025efna926dZo3b57mzp2r8ePHe+ItoRpq2LChXnrpJW3YsEHfffedbrrpJvXu3Vtbt26VxBhE1fv222/1t7/9TW3atHFqZyxWAwYe0bFjRzNs2DDH14WFheayyy4zKSkpHqwKlypJZsmSJY6v7Xa7iYmJMa+88oqj7cSJEyYwMNC8++67xhhjtm3bZiSZb7/91tHnk08+MTabzRw4cKDKasel4/Dhw0aSWb16tTGmaMz5+/ub999/39Fn+/btRpJJT083xhizfPly4+PjY7Kyshx9ZsyYYcLCwkxeXl7VvgFcMurUqWP+/ve/MwZR5U6ePGmaNm1qVq5cabp27WpGjhxpjOH7YXXBGScPyM/P14YNG5SYmOho8/HxUWJiotLT0z1YGWqKzMxMZWVlOY3B8PBwderUyTEG09PTFRERoQ4dOjj6JCYmysfHR+vXr6/ymlH95eTkSJLq1q0rSdqwYYPOnz/vNA6bN2+uRo0aOY3D1q1bKzo62tEnKSlJubm5jjMGgKsKCwu1YMECnT59WgkJCYxBVLlhw4bptttucxpzEt8Pqws/TxdQEx09elSFhYVOA1+SoqOjtWPHDg9VhZokKytLkkodg8XrsrKyFBUV5bTez89PdevWdfQBXGW32zVq1Chdf/31atWqlaSiMRYQEKCIiAinvr8dh6WN0+J1gCu+//57JSQk6Ny5cwoJCdGSJUvUsmVLbd68mTGIKrNgwQJt3LhR3377bYl1fD+sHghOAIBKN2zYMP33v//V2rVrPV0KaqCrrrpKmzdvVk5Ojj744AMlJydr9erVni4LNci+ffs0cuRIrVy5UkFBQZ4uBxeJS/U8oH79+vL19S0xU0p2drZiYmI8VBVqkuJxVtYYjImJKTFZSUFBgY4fP844hVuGDx+uZcuWadWqVWrYsKGjPSYmRvn5+Tpx4oRT/9+Ow9LGafE6wBUBAQG68sor1b59e6WkpKht27aaMmUKYxBVZsOGDTp8+LCuueYa+fn5yc/PT6tXr9bUqVPl5+en6OhoxmI1QHDygICAALVv316pqamONrvdrtTUVCUkJHiwMtQUTZo0UUxMjNMYzM3N1fr16x1jMCEhQSdOnNCGDRscfb744gvZ7XZ16tSpymtG9WOM0fDhw7VkyRJ98cUXatKkidP69u3by9/f32kcZmRkaO/evU7j8Pvvv3cK8StXrlRYWJhatmxZNW8Elxy73a68vDzGIKpM9+7d9f3332vz5s2OpUOHDhowYIDj74zFasDTs1PUVAsWLDCBgYFm7ty5Ztu2beahhx4yERERTjOlAOVx8uRJs2nTJrNp0yYjybz++utm06ZNZs+ePcYYY1566SUTERFh/v3vf5v//Oc/pnfv3qZJkybm7Nmzjn3ccsst5ne/+51Zv369Wbt2rWnatKnp16+fp94SqpmhQ4ea8PBwk5aWZg4dOuRYzpw54+jzyCOPmEaNGpkvvvjCfPfddyYhIcEkJCQ41hcUFJhWrVqZHj16mM2bN5sVK1aYyMhIM27cOE+8JVRDY8eONatXrzaZmZnmP//5jxk7dqyx2Wzms88+M8YwBuE5v55VzxjGYnVAcPKgN954wzRq1MgEBASYjh07mq+//trTJeESsmrVKiOpxJKcnGyMKZqS/NlnnzXR0dEmMDDQdO/e3WRkZDjt49ixY6Zfv34mJCTEhIWFmcGDB5uTJ0964N2gOipt/Ekyc+bMcfQ5e/asefTRR02dOnVMrVq1zB133GEOHTrktJ/du3ebW2+91QQHB5v69eubJ554wpw/f76K3w2qq/vvv980btzYBAQEmMjISNO9e3dHaDKGMQjP+W1wYix6P5sxxnjmXBcAAAAAVA/c4wQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAAAAAFghOAAAAAGCB4AQAqJFsNpuWLl3q6TIAANUEwQkAUO0MGjRIffr08XQZAIAahOAEAAAAABYITgCAaq1bt2567LHH9OSTT6pu3bqKiYnRc88959Rn586d6tKli4KCgtSyZUutXLmyxH727dunu+++WxEREapbt6569+6t3bt3S5J27NihWrVqaf78+Y7+7733noKDg7Vt27bKfHsAAC9BcAIAVHvz5s1T7dq1tX79ek2aNEl//vOfHeHIbrerb9++CggI0Pr16zVz5kw99dRTTtufP39eSUlJCg0N1Zo1a/TVV18pJCREt9xyi/Lz89W8eXO9+uqrevTRR7V3717t379fjzzyiF5++WW1bNnSE28ZAFDFbMYY4+kiAABwx6BBg3TixAktXbpU3bp1U2FhodasWeNY37FjR91000166aWX9Nlnn+m2227Tnj17dNlll0mSVqxYoVtvvVVLlixRnz599K9//UsTJ07U9u3bZbPZJEn5+fmKiIjQ0qVL1aNHD0nS7bffrtzcXAUEBMjX11crVqxw9AcAXNr8PF0AAADl1aZNG6evY2NjdfjwYUnS9u3bFRcX5whNkpSQkODUf8uWLdq1a5dCQ0Od2s+dO6cff/zR8fXs2bPVrFkz+fj4aOvWrYQmAKhBCE4AgGrP39/f6WubzSa73e7y9qdOnVL79u31zjvvlFgXGRnp+PuWLVt0+vRp+fj46NChQ4qNjb34ogEA1QrBCQBwSWvRooX27dvnFHS+/vprpz7XXHONFi5cqKioKIWFhZW6n+PHj2vQoEF6+umndejQIQ0YMEAbN25UcHBwpb8HAIDnMTkEAOCSlpiYqGbNmik5OVlbtmzRmjVr9PTTTzv1GTBggOrXr6/evXtrzZo1yszMVFpamh577DHt379fkvTII48oLi5OzzzzjF5//XUVFhZqzJgxnnhLAAAPIDgBAC5pPj4+WrJkic6ePauOHTvqwQcf1F/+8henPrVq1dKXX36pRo0aqW/fvmrRooUeeOABnTt3TmFhYfrnP/+p5cuX6+2335afn59q166tf/3rX5o1a5Y++eQTD70zAEBVYlY9AAAAALDAGScAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsEBwAgAAAAALBCcAAAAAsPD/ZTaR2xM0MWYAAAAASUVORK5CYII=",
      "text/plain": [
       "<Figure size 1000x600 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "plt.figure(figsize=(10, 6))\n",
    "plt.plot(testing_data.index, predictions, marker='o', linestyle='', color='b', label='Predictions')\n",
    "\n",
    "# Add labels and title\n",
    "plt.xlabel('Index')\n",
    "plt.ylabel('Predicted Label')\n",
    "plt.title('Predictions of the Model')\n",
    "\n",
    "# Show legend\n",
    "plt.legend()\n",
    "\n",
    "# Show plot\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7853cf8e-fcd1-4c7e-8957-6afe01fc10fe",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Listening on http://127.0.0.1:8080\n",
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62347)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62349)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:35] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:35] \"CONNECT download.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT contile.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT firefox-api-proxy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT download.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT firefox-api-proxy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('POST')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"POST http://r10.o.lencr.org/ HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT safebrowsing.googleapis.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT shavar.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT normandy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:36] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['http:', '', 'detectportal.firefox.com', 'success.txt?ipv4']\n",
      "0\n",
      "['http:', '', 'detectportal.firefox.com', 'success.txt?ipv6']\n",
      "0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:37] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:40] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:40] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:40] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:40] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:41] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:41] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:41] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:41] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:41] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:41] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:42] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:42] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:42] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:42] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:43] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:43] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:43] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:43] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:45] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:51] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:24:51] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:03] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT normandy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT services.addons.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('POST')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"POST http://r10.o.lencr.org/ HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT location.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:04] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:05] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:06] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:06] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:06] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:06] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62553)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:11] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:11] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62555)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:15] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62565)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62566)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62567)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62568)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62569)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62570)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62571)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62572)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62573)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62574)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:18] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:18] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:18] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:18] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:19] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:19] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62581)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62582)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62583)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62584)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62585)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62586)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62587)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62588)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62589)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62590)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62591)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62592)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62593)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62594)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62595)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62596)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62597)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62598)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62599)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62600)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62601)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62602)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62603)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62604)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62605)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62606)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62607)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62608)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62609)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62610)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n",
      "['', '']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62611)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62612)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62613)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62614)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62615)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62616)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62617)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62618)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62619)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "----------------------------------------\n",
      "Exception occurred during processing of request from ('127.0.0.1', 62620)\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 317, in _handle_request_noblock\n",
      "    self.process_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 348, in process_request\n",
      "    self.finish_request(request, client_address)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 361, in finish_request\n",
      "    self.RequestHandlerClass(request, client_address, self)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 671, in __init__\n",
      "    super().__init__(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\socketserver.py\", line 755, in __init__\n",
      "    self.handle()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 436, in handle\n",
      "    self.handle_one_request()\n",
      "  File \"C:\\ProgramData\\anaconda3\\Lib\\http\\server.py\", line 424, in handle_one_request\n",
      "    method()\n",
      "  File \"C:\\Users\\Rudra kumar\\AppData\\Local\\Temp\\ipykernel_2388\\2166956329.py\", line 67, in do_GET\n",
      "    self.proxy_request('http://' + parts[2] + '/')\n",
      "                                   ~~~~~^^^\n",
      "IndexError: list index out of range\n",
      "----------------------------------------\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT normandy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:27] \"CONNECT content-signature-2.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:51] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:25:51] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:05] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:06] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:06] \"CONNECT www.google.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:07] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:07] \"CONNECT www.google.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:07] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:07] \"CONNECT www.google.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:08] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:08] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:08] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:08] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:09] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:09] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:09] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:09] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['http:', '', 'demo.testfire.net', '']\n",
      "0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [31/Jul/2024 10:27:10] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:10] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:10] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:10] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:11] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:11] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:11] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:11] \"CONNECT img-getpocket.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:11] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:11] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:27:16] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['http:', '', 'demo.testfire.net', 'index.jsp?content=personal_cards.htm']\n",
      "0\n",
      "['http:', '', 'demo.testfire.net', 'index.jsp?content=business_lending.htm']\n",
      "0\n",
      "['http:', '', 'demo.testfire.net', 'search.jsp?query=hello']\n",
      "0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [31/Jul/2024 10:28:16] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:28:16] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:28:16] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:28:16] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:28:16] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:28:16] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:28:21] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:28:21] \"CONNECT aus5.mozilla.org:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['http:', '', 'demo.testfire.net', 'index.jsp?content=business.htm']\n",
      "0\n",
      "['http:', '', 'demo.testfire.net', 'index.jsp?content=personal_loans.htm']\n",
      "0\n",
      "['http:', '', 'demo.testfire.net', 'index.jsp?content=business_retirement.htm']\n",
      "0\n",
      "['http:', '', 'demo.testfire.net', 'survey_questions.jsp']\n",
      "0\n",
      "['http:', '', 'demo.testfire.net', 'index.jsp?content=inside.htm']\n",
      "0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [31/Jul/2024 10:29:40] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:29:40] \"CONNECT contile.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:29:40] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:29:40] \"CONNECT firefox-api-proxy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:29:52] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:29:52] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:34:24] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:34:24] \"CONNECT firefox.settings.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:34:40] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:34:40] \"CONNECT firefox-api-proxy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:35:12] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:35:12] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:44:27] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:44:27] \"CONNECT shavar.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:45:48] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:45:48] \"CONNECT contile.services.mozilla.com:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:45:48] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:45:48] \"CONNECT firefox-api-proxy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:45:52] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:45:52] \"CONNECT push.services.mozilla.com:443 HTTP/1.1\" 501 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "['http:', '', 'demo.testfire.net', 'index.jsp?content=personal_deposit.htm']\n",
      "0\n",
      "['http:', '', 'demo.testfire.net', 'search.jsp?query=hello']\n",
      "0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [31/Jul/2024 10:47:11] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:47:11] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:47:11] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:47:11] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:47:11] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:47:11] \"CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:50:48] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:50:48] \"CONNECT firefox-api-proxy.cdn.mozilla.net:443 HTTP/1.1\" 501 -\n",
      "127.0.0.1 - - [31/Jul/2024 10:54:32] code 501, message Unsupported method ('CONNECT')\n",
      "127.0.0.1 - - [31/Jul/2024 10:54:32] \"CONNECT safebrowsing.googleapis.com:443 HTTP/1.1\" 501 -\n"
     ]
    }
   ],
   "source": [
    "from http.server import SimpleHTTPRequestHandler, HTTPServer \n",
    "from urllib import request, error\n",
    "import numpy as np\n",
    "import pickle\n",
    "import urllib.parse\n",
    "\n",
    "badwords = ['sleep', 'uid', 'select', 'waitfor', 'delay', 'system', 'union', 'order by', 'group by', 'admin', 'drop', 'script']\n",
    "\n",
    "def ExtractFeatures(path, body):\n",
    "    path = str(path)\n",
    "    body = str(body)\n",
    "    combined_raw = path + body\n",
    "    raw_percentages = combined_raw.count(\"%\")\n",
    "    raw_spaces = combined_raw.count(\" \")\n",
    "\n",
    "    # Check if both counts exceed the threshold\n",
    "    raw_percentages_count = raw_percentages if raw_percentages > 3 else 0\n",
    "    raw_spaces_count = raw_spaces if raw_spaces > 3 else 0\n",
    "\n",
    "    # Decode the path and body for other feature extractions\n",
    "    path_decoded = urllib.parse.unquote_plus(path)\n",
    "    body_decoded = urllib.parse.unquote_plus(body)\n",
    "\n",
    "    single_q = path_decoded.count(\"'\") + body_decoded.count(\"'\")\n",
    "    double_q = path_decoded.count(\"\\\"\") + body_decoded.count(\"\\\"\")\n",
    "    dashes = path_decoded.count(\"--\") + body_decoded.count(\"--\")\n",
    "    braces = path_decoded.count(\"(\") + body_decoded.count(\"(\")\n",
    "    spaces = path_decoded.count(\" \") + body_decoded.count(\" \")\n",
    "    semicolons = path_decoded.count(\";\") + body_decoded.count(\";\")\n",
    "    angle_brackets = path_decoded.count(\"<\") + path_decoded.count(\">\") + body_decoded.count(\"<\") + body_decoded.count(\">\")\n",
    "    special_chars = sum(path_decoded.count(c) + body_decoded.count(c) for c in '$&|')\n",
    "\n",
    "    badwords_count = sum(path_decoded.lower().count(word) + body_decoded.lower().count(word) for word in badwords)\n",
    "\n",
    "    path_length = len(path_decoded)\n",
    "    body_length = len(body_decoded)\n",
    "\n",
    "    return [single_q, double_q, dashes, braces, spaces, raw_percentages_count, semicolons, angle_brackets, special_chars, path_length, body_length, badwords_count]\n",
    "\n",
    "# Define the SimpleHTTPProxy class\n",
    "class SimpleHTTPProxy(SimpleHTTPRequestHandler):\n",
    "    proxy_routes = {}\n",
    "\n",
    "    @classmethod\n",
    "    def set_routes(cls, proxy_routes):\n",
    "        cls.proxy_routes = proxy_routes\n",
    "\n",
    "    def do_GET(self):\n",
    "        parts = self.path.split('/')\n",
    "        print(parts)\n",
    "        if len(parts) > 3:\n",
    "            path_part = parts[3]\n",
    "            body = \"\"  \n",
    "            live_data = ExtractFeatures(path_part, body)\n",
    "            live_data = np.array(live_data).reshape(1, -1)  \n",
    "            \n",
    "            with open('finalized_model.pkl', 'rb') as file:\n",
    "                model = pickle.load(file)\n",
    "\n",
    "            result = model.predict(live_data) \n",
    "            print(result[0])\n",
    "            if result[0] == 1:\n",
    "                print('Intrusion Detected!!')\n",
    "                print('It is a bad request')\n",
    "        \n",
    "        if len(parts) >= 2:\n",
    "            self.proxy_request('http://' + parts[2] + '/')\n",
    "        else:\n",
    "            super().do_GET()\n",
    "\n",
    "    def proxy_request(self, url):\n",
    "        try:\n",
    "            response = request.urlopen(url)\n",
    "        except error.HTTPError as e:\n",
    "            print('err')\n",
    "            self.send_response_only(e.code)\n",
    "            self.end_headers()\n",
    "            return\n",
    "        self.send_response_only(response.status)\n",
    "        for name, value in response.headers.items():\n",
    "            self.send_header(name, value)\n",
    "        self.end_headers()\n",
    "        self.copyfile(response, self.wfile)\n",
    "\n",
    "# Set up and start the server\n",
    "SimpleHTTPProxy.set_routes({'proxy_route': 'http://demo.testfire.net/'})\n",
    "with HTTPServer(('127.0.0.1', 8080), SimpleHTTPProxy) as httpd:  # Correct reference to HTTPServer\n",
    "    host, port = httpd.socket.getsockname()\n",
    "    print(f'Listening on http://{host}:{port}')\n",
    "    try:\n",
    "        httpd.serve_forever()  \n",
    "    except KeyboardInterrupt:  \n",
    "        print(\"\\nKeyboard interrupt received, exiting.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ff52c946-1d7c-4d00-8efa-ffe67697be39",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9eb4c166-ce7a-4582-b2f8-7cd21ba00480",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
